gre_prep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('vocabulary.urls','vocabulary'), namespace='vocabulary')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vocabulary/urls.py
from django.urls import path
from .views import FamilyCreateView, index, WordCreateView, FamilyListView, FamilyDetailView, FamilyUpdateView, WordListView, PositiveConnotationListView, NegativeConnotationListView, NeutralConnotationListView, register
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path("", index, name='index'),
    path('family/create/', login_required(FamilyCreateView.as_view(), login_url= reverse_lazy('vocabulary:login')), name='family-create'),
    # path('family/list-json/', family_list_json, name='family-list-json'),
    path('family/list/', login_required(FamilyListView.as_view(),login_url= reverse_lazy('vocabulary:login')), name='family-list'),
    path('family/detail/<int:pk>/', login_required(FamilyDetailView.as_view(), login_url=reverse_lazy('vocabulary:login')), name='family-detail'),
    path('family/update/<int:pk>/', login_required(FamilyUpdateView.as_view(), login_url=reverse_lazy('vocabulary:login')), name='family-update'),
    path('word/create/', login_required(WordCreateView.as_view(), login_url=reverse_lazy('vocabulary:login')), name='word-create'),
    path('word/list/', login_required(WordListView.as_view(),login_url= reverse_lazy('vocabulary:login')), name='word-list'),
    path('connotation/positive/', login_required( PositiveConnotationListView.as_view(), login_url=reverse_lazy('vocabulary:login')), name='positive-connotation-list'),
    path('connotation/negative/', login_required(NegativeConnotationListView.as_view(), login_url=reverse_lazy('vocabulary:login')), name='negative-connotation-list'),
    path('connotation/neutral/', login_required(NeutralConnotationListView.as_view(), login_url=reverse_lazy('vocabulary:login')), name='neutral-connotation-list'),
    path('user/register/', register, name='register'),
    path('user/login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('user/logout/', LogoutView.as_view(next_page=reverse_lazy('vocabulary:index')), name='logout'),
]

vocabulary/models.py
from django.db import models

connotation_choices = [
    ('positive', 'Positive'),
    ('negative', 'Negative'),
    ('neutral', 'Neutral')
]

# Create your models here.
class Family(models.Model):
    name = models.CharField(max_length=100)
    meaning = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name

class Word(models.Model):
    name = models.CharField(max_length=100)
    connotation = models.CharField(max_length=100, choices=connotation_choices)
    definition = models.TextField(max_length=1000)

    def __str__(self) -> str:
        return self.name

class WordFamily(models.Model):
    family = models.ForeignKey(Family, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)

    def _str__(self) -> str:
        return f'{self.family.name} - {self.word.name}'

vocabulary/forms.py
from django import forms
from .models import Family, Word

class FamilyForm(forms.ModelForm):
    class Meta:
        model = Family
        fields = ['name', 'meaning', 'description']

class WordForm(forms.ModelForm):
    family = forms.ModelMultipleChoiceField(queryset=Family.objects.all(), widget=forms.SelectMultiple())
    class Meta:
        model = Word
        fields = ['name', 'connotation','definition', 'family']
    
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     families = []
    #     for family in Family.objects.all():
    #         families.append((family.id, family.name))            
    #     self.fields['family'].initial = 

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

vocabulary/views.py
from django.forms.models import BaseModelForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .models import Family, Word, WordFamily
from .forms import FamilyForm, WordForm, LoginForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required



# Create your views here.
class FamilyCreateView(CreateView):
    model = Family
    form_class = FamilyForm
    template_name = 'vocabulary/family/create.html'
    success_url = reverse_lazy('vocabulary:index')

class FamilyListView(ListView):
    model = Family
    template_name = 'vocabulary/family/list.html'

class FamilyDetailView(DetailView):
    model = Family
    template_name = 'vocabulary/family/detail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['words'] = WordFamily.objects.filter(family=self.object)
        return self.render_to_response(context)

class FamilyUpdateView(UpdateView):
    model = Family
    form_class = FamilyForm
    template_name = 'vocabulary/family/update.html'
    success_url = reverse_lazy('vocabulary:index')

def index(request):
    return render(request, 'vocabulary/index.html')

class WordCreateView(CreateView):
    model = Word
    form_class = WordForm
    template_name = 'vocabulary/word/create.html'
    success_url = reverse_lazy('vocabulary:index')

    def form_valid(self, form: BaseModelForm):
        self.object = form.save()
        families = form.cleaned_data['family']
        for family in families:
            wordfamily = WordFamily.objects.create(family=family, word=self.object)
            wordfamily.save()
        return super().form_valid(form)
    
class WordListView(ListView):
    model = Word
    template_name = 'vocabulary/word/list.html'

class PositiveConnotationListView(ListView):
    model = WordFamily
    queryset = WordFamily.objects.filter(word__connotation='positive')
    template_name = 'vocabulary/word/connotation_list.html'

class NegativeConnotationListView(ListView):
    model = WordFamily
    queryset = WordFamily.objects.filter(word__connotation='negative')
    template_name = 'vocabulary/word/connotation_list.html'

class NeutralConnotationListView(ListView):
    model = WordFamily
    queryset = WordFamily.objects.filter(word__connotation='neutral')
    template_name = 'vocabulary/word/connotation_list.html'

def family_list_json(request):
    families = Family.objects.all()
    families_list = list()
    for family in families:
        family_id = family.id
        name = family.name
        family_dict = {
            'id': family_id,
            'name': name
        }
        families_list.append(family_dict)
    context = {
        'families': families_list
    }
    return JsonResponse(context)

@login_required
def register(request):  
    if request.POST == 'POST':  
        form = UserCreationForm()  
        if form.is_valid():  
            form.save()
            return redirect('vocabulary:index')  
    else:
        form = UserCreationForm()  
        context = {  
            'form':form  
        }  
    return render(request, 'user/create.html', context)

class VocabularyLoginView(LoginView):
    template_name = 'user/login.html'
    success_url = reverse_lazy('vocabulary:index')

vocabulary/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block title%}
    {% endblock%}
</head>
<body>
    <div class="container padding-1">
        {% block content %}
        {% endblock %}
    </div>
</body>
<style>
    .title{
        text-align: center;
    }
    .padding-1{
        padding:1rem;
    }
</style>
</html>

vocabulary/templates/user/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
<link rel="stylesheet" href="{% static 'css/user/index.css' %}">
<link rel="stylesheet" href="{% static 'css/user/create_user.css'%}" media="screen and (min-width: 200px) and (max-width: 800px)">
<title>Add Word</title>
{% endblock %}
{% block content %}
        <div class="title">
            <h1>Create new User</h1>
        </div>
        <div class="form">
            <form method="POST" class="d-flex flex-column">
                {% csrf_token %}
                {{ form|crispy }}
                <div id="search-bar"></div>
                <button type="submit" class="btn btn-primary" id="submit-btn">Submit</button>
            </form>
        </div>
{% endblock %}

vocabulary/templates/user/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
<link rel="stylesheet" href="{% static 'css/user/index.css' %}">
<link rel="stylesheet" href="{% static 'css/user/create_user.css'%}" media="screen and (min-width: 200px) and (max-width: 800px)">
<title>Add Word</title>
{% endblock %}
{% block content %}
        <div class="title">
            <h1>Login</h1>
        </div>
        <div class="form">
            <form method="POST" class="d-flex flex-column">
                {% csrf_token %}
                {{ form|crispy }}
                <div id="search-bar"></div>
                <button type="submit" class="btn btn-primary" id="submit-btn">Submit</button>
            </form>
        </div>
{% endblock %}

vocabulary/templates/vocabulary/family/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    <title>Create Family</title>
    <link rel="stylesheet" href="{% static 'css/family/create.css'%}">
    <link rel="stylesheet" href="{% static 'css/family/responsive_create.css'%}" media="screen and (min-width: 200px) and (max-width: 800px)">
{% endblock %}
{% block content %}
        <div class="title">
            <h1>Create a word family</h1>
        </div>
        <div class="form">
            <form method="POST" class="form-family d-flex flex-column">
                {% csrf_token %}
                {{ form|crispy }}
                <div id="select"></div>
                <button type="submit" class="btn btn-primary btn-submit">Submit</button>
            </form>
        </div>
{% endblock %}

vocabulary/templates/vocabulary/family/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title%}
<title>Word Family Detail</title>
<link rel="stylesheet" href="{% static 'css/family/detail.css'%}">
<link rel="stylesheet" href="{% static 'css/word/connotation_mobile.css'%}" media="screen and (min-width: 200px) and (max-width: 800px)">   

{% endblock %}
{% block content %}
    <h1>Word Family Detail </h1>
    <p></p>
    <div class="word-family">
        <div class="d-flex flex-column">
            <h3> Name: {{ object.name }} </h3>
            <h3>  Common Meaning: {{object.meaning}}</h3>
            <h3> Description: {{object.description}}</h3>
        </div>
    </div>
    <hr>
    {% if words %}
    <div class="words">
        <h3>Words:</h3>
        <div class="word-row d-flex">
            <div class="col col-1">SN</div>
            <div class="col col-2">Word</div>
            <div class="col col-3">Connotation</div>
            <div class="col col-4">Definition</div>
        </div>
    {% for word in words %}
        <div class="word-row d-flex">
            <div class="col col-1"><a href="">{{forloop.counter}}</a></div>
            <div class="col col-2">{{word.word.name}}</div>
            <div class="col col-3">{{word.word.connotation}}</div>
            <div class="col col-4">{{word.word.definition}}</div>
        </div>
    {% endfor %}
    </div>
    {% endif %}
    <hr>
    <a href="{% url 'vocabulary:family-create'%}" class="btn-link">Create New Word Family</a><br>
    <a href="{% url 'vocabulary:family-list'%}" class="btn-link">Word Families</a><br>
    <a href="{% url 'vocabulary:family-update' object.id %}" class="btn-link">Update Family Details</a>
{% endblock %}

vocabulary/templates/vocabulary/family/list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Word Family List</h1>
    <div class="word-family">
        {% for family in object_list %}
            <div class="word-family-item">
                <h2><a href="{% url 'vocabulary:family-detail' family.id %}" class="text-decoration-none">{{forloop.counter}} .</a> {{ family.name }}</h2>
            </div>
        {% endfor %}
    </div>
    <a href="{% url 'vocabulary:family-create'%}" class="btn-link">Create New Word Family</a>
{% endblock %}

vocabulary/templates/vocabulary/family/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    <title>Create Family</title>
    <link rel="stylesheet" href="{% static 'css/family/create.css'%}">
    <link rel="stylesheet" href="{% static 'css/family/responsive_create.css'%}" media="screen and (min-width: 200px) and (max-width: 800px)">
{% endblock %}
{% block content %}
        <div class="title">
            <h1>Update a word family</h1>
        </div>
        <div class="form">
            <form method="POST" class="form-family d-flex flex-column">
                {% csrf_token %}
                {{ form|crispy }}
                <div id="select"></div>
                <button type="submit" class="btn btn-primary btn-submit">Submit</button>
            </form>
        </div>
{% endblock %}

vocabulary/templates/vocabulary/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<h1>Welcome to Vocabulary App</h1>
<a href="{% url 'vocabulary:family-create'%}">Create Family</a><br>
<a href="{% url 'vocabulary:family-list'%}">Family List</a><br>
<a href="{% url 'vocabulary:word-create'%}">Add Words</a><br>
<a href="{% url 'vocabulary:word-list'%}">Word Lists</a><br>
<a href="{% url 'vocabulary:positive-connotation-list'%}">Positive Connotations</a><br>
<a href="{% url 'vocabulary:negative-connotation-list'%}">Negative Connotations</a><br>
<a href="{% url 'vocabulary:neutral-connotation-list'%}">Neutral Connotations</a><br>
<a href="{% url 'vocabulary:logout'%}">Logout</a><br>
{% else %}
<a href="{% url 'vocabulary:login'%}">Login</a><br>
{% endif %}
{% endblock %}

vocabulary/templates/vocabulary/word/connotation_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title%}
<title>Word Family Detail</title>
<link rel="stylesheet" href="{% static 'css/family/detail.css'%}">
<link rel="stylesheet" href="{% static 'css/word/connotation_mobile.css'%}" media="screen and (min-width: 200px) and (max-width: 800px)">
{% endblock %}
{% block content %}
    <h1>Word List</h1>
    <div class="word-family">
        <div class="words">
            <h3>Connotation Words</h3>
            <div class="word-row d-flex">
                <div class="col col-1">SN</div>
                <div class="col col-2">Word</div>
                <div class="col col-3">Family</div>
                <div class="col col-4">Deifinition</div>
            </div>        
                {% for object in object_list %}
                    <div class="word-row d-flex">
                        <div class="col col-1"><a href="">{{forloop.counter}}</a></div>
                        <div class="col col-2">{{object.word.name}}</div>
                        <div class="col col-3">{{object.family.name}}</div>
                        <div class="col col-4">{{object.word.definition}}</div>
                    </div>
                {% endfor %}
        </div>
    </div>
    <hr>
    <a href="{% url 'vocabulary:family-create'%}" class="btn-link">Create New Word Family</a>
{% endblock %}

vocabulary/templates/vocabulary/word/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/word/create_mobile.css'%}" media="screen and (min-width: 200px) and (max-width: 800px)">
<script src="{% static 'js/word_create.js'%}"></script>
<title>Add Word</title>
{% endblock %}
{% block content %}
        <div class="title">
            <h1>Add a word and its family</h1>
        </div>
        <div class="form">
            <form method="POST" class="d-flex flex-column">
                {% csrf_token %}
                {{ form|crispy }}
                <div id="search-bar"></div>
                <button type="submit" class="btn btn-primary" id="submit-btn">Submit</button>
            </form>
        </div>
{% endblock %}

vocabulary/templates/vocabulary/word/list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Word List</h1>
    <div class="word-family">
        {% for object in object_list %}
            <div class="word-family-item">
                <h2><a href="#" class="text-decoration-none"> {{forloop.counter}} . </a>{{object.name}}</h2>
            </div>
        {% endfor %}
    </div>
    <a href="{% url 'vocabulary:family-create'%}" class="btn-link">Create New Word Family</a>
{% endblock %}